import { Geist, Geist_Mono } from "next/font/google";
import "../styles/main.css";
import Providers from "../context/Providers.jsx"


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Ecommerce Site",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="light" style={{colorScheme:"light"}}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
      >
        <Providers >{children}</Providers>
      </body>
    </html>
  );
}
